Add option to enable pretty URLS
nextcloud-snap/nextcloud-snap pull request #1794
Opened 2021-07-18 20:14 UTC by szaimen

Fix https://github.com/nextcloud/nextcloud-snap/issues/412

---

It works this way: every push that is pushed to any branch that is not called master, develop or '[12][0-9]' (this regex covers 10-29) will trigger the new workflow that downloads the current branch, runs the script that I wrote (My script basically enables pretty urls for the temporary Nextcloud instance and writes all needed changes into a new .htaccess file.), changes the new .htaccess file to be based on the in the branch used nextcloud archive, commits the changes (if any) and pushes them to the same branch. This way you will be able to track any possible changes in the htaccess file in new Nextcloud versions in the future before merging into any of the mentioned branches.

If the feature gets enabled by the user it just includes my new .htaccess file in the apache conf which will automatically enable pretty urls for the users Nexcloud instance.

Signed-off-by: szaimen <szaimen@e.mail.de>

2021-07-18 20:22 UTC, szaimen commented
@kyrofa this is now much improved since it sets up a temporary Nextcloud instance, runs the normal command to enable pretty urls and writes the needed changes to the htaccess file. It is now much less of an hack than before and is hopefully integratable.

2021-08-20 15:04 UTC, szaimen commented
@kyrofa do you have some thoughts on this new attempt?

2021-09-20 20:25 UTC, kyrofa requested changes
You're right @szaimen, this is improved, but it still has the same root problem of #1700: I'm not willing to land something that automatically pushes code to a PR. I believe PRs should be owned by the author as much as possible. I would much rather see this type of thing happening during the build of the snap instead of the approach currently taken.

By the way, there was no need to re-create this PR. Just push new commits!

2021-09-20 22:44 UTC, szaimen commented
I fear i will not be able to work on this anymore. But feel free to work on this @kyrofa and use my work as base for fixing the mentioned issue.

2021-09-20 22:46 UTC, kyrofa commented
Thanks @szaimen! I'll go ahead and close this for now, then.

2021-09-20 22:46 UTC, closed without merging