Better document nextcloud.import in README
nextcloud-snap/nextcloud-snap pull request #2364
Opened 2023-03-29 14:39 UTC by dsofeir

There is essential advice about restoring backups contained in the [wiki](https://github.com/nextcloud-snap/nextcloud-snap/wiki/How-to-backup-your-instance). Without this information I spent 40 minutes trying to understand vague rsync errors. I think other users would benefit by this information being placed in a more prominent position.

2023-03-29 15:08 UTC, kyrofa requested changes
Good call. However, the README is designed to be more of a brief overview rather than all-encompassing. How would you feel about putting it in the [help text of the command itself](https://github.com/nextcloud-snap/nextcloud-snap/blob/0c472ebaaa9ddda00c52805ae5c0e2c12042dfdb/src/import-export/bin/import-data#L20)?

2023-03-29 21:57 UTC, dsofeir commented
I think the current problem is that discovery is hard. I checked the README and command help text and saw no mention it was a reddit post that guided me to the Wiki.

Given this, yes, I am in favour of putting it either in the README or command help text. Either would be helpful.

2023-05-30 17:41 UTC, kyrofa commented
Yeah I'd prefer to see it in the help text, please.

2023-06-15 19:46 UTC, Pilzinsel64 commented
Closing as already resolved in #2433

2023-06-15 19:46 UTC, closed without merging