Remove mdns
nextcloud-snap/nextcloud-snap pull request #2444
Opened 2023-07-05 08:28 UTC by Pilzinsel64

Removes all mdns references to solve the actual build error and fixes #2443.

2023-07-05 08:30 UTC, Pilzinsel64 commented
Does this go to `master` or `develop`? Would be needed in `master` ASAP to fix the daily but `develop` should be also fine if we merge #2442 soon.

2023-07-05 16:09 UTC, kyrofa commented
Yeah essentially everything to develop, please. I'll just rebase #2242.

2023-07-05 16:31 UTC, kyrofa commented on src/patches/mysql-support-compile-time-disabling-of-setpriority.patch
Good catch, this should have been removed with 0f534193a67b6c9d283b2271ba8567a876247365. However, it's easier to review and revert and in general maintain things if we keep PRs focused on one specific thing. Would you mind proposing the removal of this file in its own PR?

2023-07-05 16:32 UTC, kyrofa requested changes
Nice work. You got all the technical details, but would you mind also updating the README to remove mentions of mDNS and network discovery?

2023-07-05 16:46 UTC, Pilzinsel64 commented on src/patches/mysql-support-compile-time-disabling-of-setpriority.patch
True. I moved it to #2445

2023-07-05 16:50 UTC, Pilzinsel64 commented
> ... I (or you) can just rebase #2242.

Sure that you refered the right PR? 😅

> ... but would you mind also updating the README to remove mentions of mDNS and network discovery?

Done. Should be just the one line at the top.

2023-07-06 10:10 UTC, scubamuc approved these changes

2023-07-06 13:14 UTC, kyrofa approved these changes

2023-07-06 13:27 UTC, Pilzinsel64 commented
And now it's just one single commit - thanks @kyrofa 
Still not sure how you freely can edit the history. I always just "Squash and commit" on other repos, haha.

2023-07-06 14:40 UTC, merged