Update README.md to Nextcloud 28
nextcloud-snap/nextcloud-snap pull request #2761
Opened 2024-06-01 18:35 UTC by LMRW

The readme is out of date

2024-06-02 09:56 UTC, scubamuc approved these changes

2024-06-02 11:24 UTC, Pilzinsel64 requested changes
Huh, have rebased and target to `develop` as only release PRs get into `master`. But finally forgot to approve... 🤦‍♂

2024-06-02 11:24 UTC, merged

2024-06-02 11:36 UTC, LMRW commented
Sorry, i'll target develop next time

2024-06-03 08:53 UTC, pachulo commented
Well, this is actually wrong, as [the version on develop is 29 already](https://github.com/nextcloud-snap/nextcloud-snap/blob/develop/snap/snapcraft.yaml#L184).

But fear not, we can fix the README in the next PRs.